// Code generated by go-enum
// DO NOT EDIT!

package example

import (
	"database/sql/driver"
	"fmt"
)

const (
	// ProjectStatusPending is a ProjectStatus of type Pending
	ProjectStatusPending ProjectStatus = iota
	// ProjectStatusInWork is a ProjectStatus of type InWork
	ProjectStatusInWork
	// ProjectStatusCompleted is a ProjectStatus of type Completed
	ProjectStatusCompleted
	// ProjectStatusRejected is a ProjectStatus of type Rejected
	ProjectStatusRejected
)

const _ProjectStatusName = "pendinginWorkcompletedrejected"

var _ProjectStatusMap = map[ProjectStatus]string{
	0: _ProjectStatusName[0:7],
	1: _ProjectStatusName[7:13],
	2: _ProjectStatusName[13:22],
	3: _ProjectStatusName[22:30],
}

// String implements the Stringer interface.
func (x ProjectStatus) String() string {
	if str, ok := _ProjectStatusMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ProjectStatus(%d)", x)
}

var _ProjectStatusValue = map[string]ProjectStatus{
	_ProjectStatusName[0:7]:   0,
	_ProjectStatusName[7:13]:  1,
	_ProjectStatusName[13:22]: 2,
	_ProjectStatusName[22:30]: 3,
}

// ParseProjectStatus attempts to convert a string to a ProjectStatus
func ParseProjectStatus(name string) (ProjectStatus, error) {
	if x, ok := _ProjectStatusValue[name]; ok {
		return x, nil
	}
	return ProjectStatus(0), fmt.Errorf("%s is not a valid ProjectStatus", name)
}

func (x ProjectStatus) Ptr() *ProjectStatus {
	return &x
}

// Scan implements the Scanner interface.
func (x *ProjectStatus) Scan(value interface{}) (err error) {
	if value == nil {
		*x = ProjectStatus(0)
		return
	}

	// A wider range of scannable types.
	switch v := value.(type) {
	case *ProjectStatus:
		*x = *v
	case ProjectStatus:
		*x = v
	case int:
		*x = ProjectStatus(v)
	case int64:
		*x = ProjectStatus(v)
	case uint:
		*x = ProjectStatus(v)
	case uint64:
		*x = ProjectStatus(v)
	case *int:
		*x = ProjectStatus(*v)
	case *int64:
		*x = ProjectStatus(*v)
	case *uint:
		*x = ProjectStatus(*v)
	case *uint64:
		*x = ProjectStatus(*v)
	case string:
		*x, err = ParseProjectStatus(v)
	case *string:
		*x, err = ParseProjectStatus(*v)
	case []byte:
		*x, err = ParseProjectStatus(string(v))
	}

	return
}

// Value implements the driver Valuer interface.
func (x ProjectStatus) Value() (driver.Value, error) {
	return x.String(), nil
}

type NullProjectStatus struct {
	ProjectStatus ProjectStatus
	Valid         bool
}

func NewNullProjectStatus(val interface{}) (x NullProjectStatus) {
	x.Scan(val) // yes, we ignore this error, it will just be an invalid value.
	return
}

// Scan implements the Scanner interface.
func (x *NullProjectStatus) Scan(value interface{}) (err error) {
	if value == nil {
		x.ProjectStatus, x.Valid = ProjectStatus(0), false
		return
	}

	err = x.ProjectStatus.Scan(value)
	x.Valid = (err == nil)
	return
}

// Value implements the driver Valuer interface.
func (x NullProjectStatus) Value() (driver.Value, error) {
	if !x.Valid {
		return nil, nil
	}
	// driver.Value accepts int64 for int values.
	return int64(x.ProjectStatus), nil
}

type NullProjectStatusStr struct {
	NullProjectStatus
}

func NewNullProjectStatusStr(val interface{}) (x NullProjectStatusStr) {
	x.Scan(val) // yes, we ignore this error, it will just be an invalid value.
	return
}

// Value implements the driver Valuer interface.
func (x NullProjectStatusStr) Value() (driver.Value, error) {
	if !x.Valid {
		return nil, nil
	}
	return x.ProjectStatus.String(), nil
}
