// Code generated by go-enum
// DO NOT EDIT!

package example

import (
	"database/sql/driver"
	"fmt"
)

const (
	// ProjectStatusPending is a ProjectStatus of type Pending
	ProjectStatusPending ProjectStatus = iota
	// ProjectStatusInWork is a ProjectStatus of type InWork
	ProjectStatusInWork
	// ProjectStatusCompleted is a ProjectStatus of type Completed
	ProjectStatusCompleted
	// ProjectStatusRejected is a ProjectStatus of type Rejected
	ProjectStatusRejected
)

const _ProjectStatusName = "pendinginWorkcompletedrejected"

var _ProjectStatusMap = map[ProjectStatus]string{
	0: _ProjectStatusName[0:7],
	1: _ProjectStatusName[7:13],
	2: _ProjectStatusName[13:22],
	3: _ProjectStatusName[22:30],
}

// String implements the Stringer interface.
func (x ProjectStatus) String() string {
	if str, ok := _ProjectStatusMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ProjectStatus(%d)", x)
}

var _ProjectStatusValue = map[string]ProjectStatus{
	_ProjectStatusName[0:7]:   0,
	_ProjectStatusName[7:13]:  1,
	_ProjectStatusName[13:22]: 2,
	_ProjectStatusName[22:30]: 3,
}

// ParseProjectStatus attempts to convert a string to a ProjectStatus
func ParseProjectStatus(name string) (ProjectStatus, error) {
	if x, ok := _ProjectStatusValue[name]; ok {
		return x, nil
	}
	return ProjectStatus(0), fmt.Errorf("%s is not a valid ProjectStatus", name)
}

// Scan implements the Scanner interface.
func (x *ProjectStatus) Scan(value interface{}) error {
	var name string

	switch v := value.(type) {
	case string:
		name = v
	case []byte:
		name = string(v)
	case nil:
		*x = ProjectStatus(0)
		return nil
	}

	tmp, err := ParseProjectStatus(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// Value implements the driver Valuer interface.
func (x ProjectStatus) Value() (driver.Value, error) {
	return x.String(), nil
}
