// Code generated by go-enum DO NOT EDIT.
// Version: example
// Revision: example
// Build Date: example
// Built By: example

package example

import (
	"errors"
	"fmt"
	"strings"
)

const (
	// ColorBlack is a Color of type Black.
	ColorBlack Color = iota
	// ColorWhite is a Color of type White.
	ColorWhite
	// ColorRed is a Color of type Red.
	ColorRed
	// ColorGreen is a Color of type Green.
	// Green starts with 33
	ColorGreen Color = iota + 30
	// ColorBlue is a Color of type Blue.
	ColorBlue
	// ColorGrey is a Color of type Grey.
	ColorGrey
	// ColorYellow is a Color of type Yellow.
	ColorYellow
	// ColorBlueGreen is a Color of type Blue-Green.
	ColorBlueGreen
	// ColorRedOrange is a Color of type Red-Orange.
	ColorRedOrange
	// ColorYellowGreen is a Color of type Yellow_green.
	ColorYellowGreen
	// ColorRedOrangeBlue is a Color of type Red-Orange-Blue.
	ColorRedOrangeBlue
)

var ErrInvalidColor = errors.New("not a valid Color")

const _colorName = "BlackWhiteRedGreenBluegreyyellowblue-greenred-orangeyellow_greenred-orange-blue"

var _colorMap = map[Color]string{
	ColorBlack:         _colorName[0:5],
	ColorWhite:         _colorName[5:10],
	ColorRed:           _colorName[10:13],
	ColorGreen:         _colorName[13:18],
	ColorBlue:          _colorName[18:22],
	ColorGrey:          _colorName[22:26],
	ColorYellow:        _colorName[26:32],
	ColorBlueGreen:     _colorName[32:42],
	ColorRedOrange:     _colorName[42:52],
	ColorYellowGreen:   _colorName[52:64],
	ColorRedOrangeBlue: _colorName[64:79],
}

// String implements the Stringer interface.
func (x Color) String() string {
	if str, ok := _colorMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Color(%d)", x)
}

var _colorValue = map[string]Color{
	_colorName[0:5]:                    ColorBlack,
	strings.ToLower(_colorName[0:5]):   ColorBlack,
	_colorName[5:10]:                   ColorWhite,
	strings.ToLower(_colorName[5:10]):  ColorWhite,
	_colorName[10:13]:                  ColorRed,
	strings.ToLower(_colorName[10:13]): ColorRed,
	_colorName[13:18]:                  ColorGreen,
	strings.ToLower(_colorName[13:18]): ColorGreen,
	_colorName[18:22]:                  ColorBlue,
	strings.ToLower(_colorName[18:22]): ColorBlue,
	_colorName[22:26]:                  ColorGrey,
	strings.ToLower(_colorName[22:26]): ColorGrey,
	_colorName[26:32]:                  ColorYellow,
	strings.ToLower(_colorName[26:32]): ColorYellow,
	_colorName[32:42]:                  ColorBlueGreen,
	strings.ToLower(_colorName[32:42]): ColorBlueGreen,
	_colorName[42:52]:                  ColorRedOrange,
	strings.ToLower(_colorName[42:52]): ColorRedOrange,
	_colorName[52:64]:                  ColorYellowGreen,
	strings.ToLower(_colorName[52:64]): ColorYellowGreen,
	_colorName[64:79]:                  ColorRedOrangeBlue,
	strings.ToLower(_colorName[64:79]): ColorRedOrangeBlue,
}

// ParseColor attempts to convert a string to a Color.
func ParseColor(name string) (Color, error) {
	if x, ok := _colorValue[name]; ok {
		return x, nil
	}
	return Color(0), fmt.Errorf("%s is %w", name, ErrInvalidColor)
}

// MustParseColor converts a string to a Color, and panics if is not valid.
func MustParseColor(name string) Color {
	val, err := ParseColor(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x Color) Ptr() *Color {
	return &x
}

// MarshalText implements the text marshaller method.
func (x Color) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Color) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseColor(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
