// Code generated by go-enum DO NOT EDIT.
// Version: example
// Revision: example
// Build Date: example
// Built By: example

package example

import (
	"errors"
	"fmt"
	"strings"
)

const (
	// AllNegativeUnknown is a AllNegative of type Unknown.
	AllNegativeUnknown AllNegative = iota + -5
	// AllNegativeGood is a AllNegative of type Good.
	AllNegativeGood
	// AllNegativeBad is a AllNegative of type Bad.
	AllNegativeBad
	// AllNegativeUgly is a AllNegative of type Ugly.
	AllNegativeUgly
)

var ErrInvalidAllNegative = errors.New("not a valid AllNegative")

const _allNegativeName = "UnknownGoodBadUgly"

var _allNegativeMap = map[AllNegative]string{
	AllNegativeUnknown: _allNegativeName[0:7],
	AllNegativeGood:    _allNegativeName[7:11],
	AllNegativeBad:     _allNegativeName[11:14],
	AllNegativeUgly:    _allNegativeName[14:18],
}

// String implements the Stringer interface.
func (x AllNegative) String() string {
	if str, ok := _allNegativeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("AllNegative(%d)", x)
}

var _allNegativeValue = map[string]AllNegative{
	_allNegativeName[0:7]:                    AllNegativeUnknown,
	strings.ToLower(_allNegativeName[0:7]):   AllNegativeUnknown,
	_allNegativeName[7:11]:                   AllNegativeGood,
	strings.ToLower(_allNegativeName[7:11]):  AllNegativeGood,
	_allNegativeName[11:14]:                  AllNegativeBad,
	strings.ToLower(_allNegativeName[11:14]): AllNegativeBad,
	_allNegativeName[14:18]:                  AllNegativeUgly,
	strings.ToLower(_allNegativeName[14:18]): AllNegativeUgly,
}

// ParseAllNegative attempts to convert a string to a AllNegative.
func ParseAllNegative(name string) (AllNegative, error) {
	if x, ok := _allNegativeValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _allNegativeValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return AllNegative(0), fmt.Errorf("%s is %w", name, ErrInvalidAllNegative)
}

const (
	// StatusUnknown is a Status of type Unknown.
	StatusUnknown Status = iota + -1
	// StatusGood is a Status of type Good.
	StatusGood
	// StatusBad is a Status of type Bad.
	StatusBad
)

var ErrInvalidStatus = errors.New("not a valid Status")

const _statusName = "UnknownGoodBad"

var _statusMap = map[Status]string{
	StatusUnknown: _statusName[0:7],
	StatusGood:    _statusName[7:11],
	StatusBad:     _statusName[11:14],
}

// String implements the Stringer interface.
func (x Status) String() string {
	if str, ok := _statusMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Status(%d)", x)
}

var _statusValue = map[string]Status{
	_statusName[0:7]:                    StatusUnknown,
	strings.ToLower(_statusName[0:7]):   StatusUnknown,
	_statusName[7:11]:                   StatusGood,
	strings.ToLower(_statusName[7:11]):  StatusGood,
	_statusName[11:14]:                  StatusBad,
	strings.ToLower(_statusName[11:14]): StatusBad,
}

// ParseStatus attempts to convert a string to a Status.
func ParseStatus(name string) (Status, error) {
	if x, ok := _statusValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _statusValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return Status(0), fmt.Errorf("%s is %w", name, ErrInvalidStatus)
}
