// Code generated by go-enum DO NOT EDIT.
// Version: example
// Revision: example
// Build Date: example
// Built By: example

package example

import (
	"fmt"
	"strings"
)

const (
	// AcmeInt_SOME_PLACE_AWESOME is a IntShop of type SOME_PLACE_AWESOME.
	AcmeInt_SOME_PLACE_AWESOME IntShop = iota
	// AcmeInt_SomewhereElse is a IntShop of type SomewhereElse.
	AcmeInt_SomewhereElse
	// AcmeInt_LocationUnknown is a IntShop of type LocationUnknown.
	AcmeInt_LocationUnknown
)

var _intShopNames = []string{
	_intShopName[0:18],
	_intShopName[18:31],
	_intShopName[31:46],
}

// IntShopNames returns a list of possible string values of IntShop.
func IntShopNames() []string {
	tmp := make([]string, len(_intShopNames))
	copy(tmp, _intShopNames)
	return tmp
}

var ErrInvalidIntShop = fmt.Errorf("not a valid IntShop, try [%s]", strings.Join(_intShopNames, ", "))

const _intShopName = "SOME_PLACE_AWESOMESomewhereElseLocationUnknown"

var _intShopMap = map[IntShop]string{
	AcmeInt_SOME_PLACE_AWESOME: _intShopName[0:18],
	AcmeInt_SomewhereElse:      _intShopName[18:31],
	AcmeInt_LocationUnknown:    _intShopName[31:46],
}

// String implements the Stringer interface.
func (x IntShop) String() string {
	if str, ok := _intShopMap[x]; ok {
		return str
	}
	return fmt.Sprintf("IntShop(%d)", x)
}

var _intShopValue = map[string]IntShop{
	_intShopName[0:18]:  AcmeInt_SOME_PLACE_AWESOME,
	_intShopName[18:31]: AcmeInt_SomewhereElse,
	_intShopName[31:46]: AcmeInt_LocationUnknown,
}

// ParseIntShop attempts to convert a string to a IntShop.
func ParseIntShop(name string) (IntShop, error) {
	if x, ok := _intShopValue[name]; ok {
		return x, nil
	}
	return IntShop(0), fmt.Errorf("%s is %w", name, ErrInvalidIntShop)
}

// MarshalText implements the text marshaller method.
func (x IntShop) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *IntShop) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseIntShop(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
